"""add secondary_diagnosis to patients

Revision ID: 7d5a3c84f2b1
Revises: 6ea6b2970f09
Create Date: 2025-09-04 00:30:00.0000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5a3c84f2b1'
down_revision = '6ea6b2970f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('secondary_diagnosis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'secondary_diagnosis')
    # ### end Alembic commands ###