"""Add doctor_patient_association table

Revision ID: 82780d4846db
Revises: 263c335ffb32
Create Date: 2025-05-01 00:05:18.364256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82780d4846db'
down_revision: Union[str, None] = '263c335ffb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_patient_association',
    sa.Column('doctor_user_id', sa.Integer(), nullable=False),
    sa.Column('patient_patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_user_id', 'patient_patient_id')
    )
    
    # Apply changes to health_diary_entries using batch mode
    with op.batch_alter_table('health_diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        # Drop index needs correct name if generated with batch_op.f
        # If index was created manually, use exact name 'ix_health_diary_entries_entry_date'
        try:
             batch_op.drop_index('ix_health_diary_entries_entry_date') 
        except Exception as e:
            print(f"Could not drop index ix_health_diary_entries_entry_date (might not exist): {e}")
        batch_op.drop_column('symptoms')
        batch_op.drop_column('entry_date')
        batch_op.drop_column('notes')
        batch_op.drop_column('mood')
        batch_op.drop_column('activity_level')

    # Apply changes to health_tips using batch mode
    with op.batch_alter_table('health_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.drop_column('is_general')
        # Assuming 'content' and 'title' columns were also removed previously
        batch_op.drop_column('content') 
        batch_op.drop_column('title')
        batch_op.drop_column('source')
        batch_op.drop_column('category')

    # Apply changes to patients table using batch mode for constraint
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_patients_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Downgrade patients table constraint using batch mode
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patients_user_id'), type_='unique')

    # Downgrade health_tips using batch mode
    with op.batch_alter_table('health_tips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('is_general', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('text')

    # Downgrade health_diary_entries using batch mode
    with op.batch_alter_table('health_diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_level', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('entry_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('symptoms', sa.TEXT(), nullable=True))
        # Recreate index if needed, using batch_op.f for naming convention
        batch_op.create_index(batch_op.f('ix_health_diary_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.drop_column('content')

    op.drop_table('doctor_patient_association')
    # ### end Alembic commands ###
