###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class AnalyzeDifferentialDiagnosesSNAPPSInput(BaseModel):
    case_summary: Optional[str] = None
    student_differential_diagnoses: List[str]
    case_context: Optional[str] = None

class AnswerProbeQuestionsSNAPPSInputModel(BaseModel):
    session_context: Optional[str] = None
    student_questions: Optional[str] = None
    case_data: Optional[str] = None

class AnsweredQuestion(BaseModel):
    question: Optional[str] = None
    answer: Optional[str] = None
    rationale: Optional[str] = None

class BAMLProblemRepresentationInput(BaseModel):
    full_patient_narrative: Optional[str] = None
    user_problem_representation: Optional[str] = None
    user_semantic_qualifiers: List[str]

class BenchmarkComparison(BaseModel):
    industry_percentile: Optional[float] = None
    performance_grade: Optional[str] = None
    benchmark_insights: List[str]
    improvement_targets: List[str]

class BiasAssessment(BaseModel):
    bias_type: Optional[str] = None
    risk_level: Optional[str] = None
    explanation: Optional[str] = None
    mitigation_strategies: List[str]

class CaseContext(BaseModel):
    demographics: Optional[str] = None
    chief_complaint: Optional[str] = None
    physical_exam: Optional[str] = None
    vital_signs: Optional[str] = None
    full_description: Optional[str] = None
    expected_differentials: Optional[List[str]] = None
    learning_objectives: Optional[List[str]] = None
    expert_analysis: Optional[str] = None

class CaseScenarioInput(BaseModel):
    case_vignette: Optional[str] = None
    initial_findings: List["ClinicalFinding"]
    plausible_hypotheses: List[str]

class CiteSourceAnalysisInput(BaseModel):
    search_results: List["RawSearchResultItem"]
    query: Optional[str] = None
    include_visualization_data: Optional[bool] = None

class CiteSourceAnalysisOutput(BaseModel):
    deduplication_summary: Optional["DeduplicationSummary"] = None
    source_performance: List["SourcePerformanceMetrics"]
    quality_assessment: Optional["QualityScores"] = None
    processing_insights: List[str]
    recommendations: List[str]
    deduplicated_results: List["RawSearchResultItem"]
    processing_metadata: Optional["ProcessingMetadata"] = None

class CiteSourceMetrics(BaseModel):
    total_sources_consulted: Optional[int] = None
    original_results_count: Optional[int] = None
    deduplicated_results_count: Optional[int] = None
    deduplication_rate: Optional[float] = None
    overall_quality_score: Optional[float] = None
    coverage_score: Optional[float] = None
    diversity_score: Optional[float] = None
    recency_score: Optional[float] = None
    impact_score: Optional[float] = None
    source_balance_score: Optional[float] = None
    best_performing_source: Optional[str] = None
    processing_time_ms: Optional[float] = None
    key_quality_insights: List[str]

class CiteSourceReportInput(BaseModel):
    query: Optional[str] = None
    max_results: Optional[int] = None
    include_detailed_metrics: Optional[bool] = None
    include_recommendations: Optional[bool] = None

class CiteSourceReportOutput(BaseModel):
    executive_summary: Optional["ExecutiveSummary"] = None
    quality_breakdown: Optional["QualityScores"] = None
    source_analysis: Optional["SourceAnalysis"] = None
    deduplication_analysis: Optional["DeduplicationAnalysis"] = None
    actionable_insights: List[str]
    benchmark_comparison: Optional["BenchmarkComparison"] = None
    visual_data_summary: Optional["VisualDataSummary"] = None
    disclaimer: Optional[str] = None

class ClinicalApplicationAssessment(BaseModel):
    clinical_relevance: Optional[str] = None
    patient_population_match: Optional[str] = None
    outcome_relevance: Optional[str] = None
    practical_feasibility: Optional[str] = None
    cost_effectiveness_considerations: Optional[str] = None
    ethical_considerations: List[str]

class ClinicalDataInput(BaseModel):
    patient_story: Optional[str] = None
    known_findings: List["ClinicalFinding"]
    patient_demographics: Optional[str] = None

class ClinicalFinding(BaseModel):
    finding_name: Optional[str] = None
    details: Optional[str] = None
    onset_duration_pattern: Optional[str] = None
    severity_level: Optional[str] = None

class ClinicalScenarioInput(BaseModel):
    clinical_scenario: Optional[str] = None
    additional_context: Optional[str] = None

class ClinicalWorkflowQuestionsOutput(BaseModel):
    question_categories: List["QuestionCategory"]
    red_flag_questions: List[str]
    overall_rationale: Optional[str] = None

class CognitiveBiasInput(BaseModel):
    case_summary_by_user: Optional[str] = None
    user_working_hypothesis: Optional[str] = None
    user_reasoning_summary: Optional[str] = None

class CognitiveBiasReflectionOutput(BaseModel):
    potential_biases_to_consider: List["DetectedCognitiveBias"]

class CompareContrastExerciseInput(BaseModel):
    scenario: Optional["CaseScenarioInput"] = None
    student_analysis: List["StudentHypothesisAnalysis"]

class CompareContrastFeedbackOutput(BaseModel):
    overall_feedback: Optional[str] = None
    detailed_feedback_per_hypothesis: List["HypothesisComparisonFeedback"]
    suggested_learning_focus: Optional[str] = None

class DdxEvaluation(BaseModel):
    diagnosis: Optional[str] = None
    plausibility: Optional[str] = None
    supporting_findings: List[str]
    contradicting_findings: List[str]

class DdxQuestioningInput(BaseModel):
    chief_complaint: Optional[str] = None
    initial_findings: List["ClinicalFinding"]
    patient_demographics: Optional[str] = None

class DdxQuestioningOutput(BaseModel):
    prioritized_questions: List[str]
    complementary_questions: List[str]
    questioning_rationale: Optional[str] = None
    potential_systems_to_explore: List[str]

class DeduplicationAnalysis(BaseModel):
    efficiency_metrics: Optional["DeduplicationSummary"] = None
    duplication_patterns: List[str]
    source_overlap_analysis: Optional[str] = None
    optimization_suggestions: List[str]

class DeduplicationSummary(BaseModel):
    original_count: Optional[int] = None
    deduplicated_count: Optional[int] = None
    removed_duplicates: Optional[int] = None
    deduplication_rate: Optional[float] = None
    efficiency_score: Optional[float] = None

class DetectedCognitiveBias(BaseModel):
    bias_type: Optional[str] = None
    explanation_as_question: Optional[str] = None
    mitigation_prompt: Optional[str] = None

class DiagnosticTimeoutInput(BaseModel):
    case_description: Optional[str] = None
    current_working_diagnosis: Optional[str] = None
    time_elapsed_minutes: Optional[int] = None
    complexity_level: Optional[str] = None

class DiagnosticTimeoutOutput(BaseModel):
    timeout_recommendation: Optional[str] = None
    alternative_diagnoses_to_consider: List[str]
    key_questions_to_ask: List[str]
    red_flags_to_check: List[str]
    next_steps_suggested: List[str]
    cognitive_checks: List[str]

class DifferentialAnalysisOutputModel(BaseModel):
    ddx_evaluation: List["DdxEvaluation"]
    missing_differentials: List[str]
    prioritization_feedback: Optional[str] = None
    socratic_questions: List[str]
    next_step_guidance: Optional[str] = None

class EnhancedAppraisalOutput(BaseModel):
    identified_study_type: Optional[str] = None
    study_design_appropriateness: Optional[str] = None
    quality_assessment: Optional["QualityAssessment"] = None
    methodological_strengths: List[str]
    methodological_limitations: List[str]
    bias_assessments: List["BiasAssessment"]
    overall_bias_risk: Optional[str] = None
    statistical_assessment: Optional["StatisticalAssessment"] = None
    clinical_application: Optional["ClinicalApplicationAssessment"] = None
    pico_alignment_assessment: Optional[str] = None
    population_match_percentage: Optional[str] = None
    intervention_comparability: Optional[str] = None
    outcome_relevance_score: Optional[str] = None
    strength_of_recommendation: Optional[str] = None
    level_of_evidence: Optional[str] = None
    confidence_in_findings: Optional[str] = None
    recommendations_for_practice: List[str]
    areas_requiring_more_research: List[str]
    next_steps_for_evidence_evaluation: List[str]
    key_clinical_considerations: List[str]
    potential_harms_or_risks: List[str]
    patient_preference_factors: List[str]
    generalizability_assessment: Optional[str] = None
    external_validity_concerns: List[str]
    study_limitations_impact: Optional[str] = None
    learning_points: List[str]
    critical_appraisal_checklist: List[str]
    evidence_synthesis_date: Optional[str] = None

class EvaluateManagementPlanSNAPPSInputModel(BaseModel):
    session_context: Optional[str] = None
    student_plan: Optional[str] = None
    case_data: Optional[str] = None

class EvaluateSummarySNAPPSInputModel(BaseModel):
    student_summary: Optional[str] = None
    case_description: Optional[str] = None

class EvidenceAppraisalInput(BaseModel):
    clinical_question_PICO: Optional[str] = None
    evidence_summary_or_abstract: Optional[str] = None
    study_type_if_known: Optional[str] = None

class EvidenceTheme(BaseModel):
    theme_name: Optional[str] = None
    key_findings: List[str]
    strength_of_evidence: Optional[str] = None
    supporting_studies_count: Optional[int] = None

class ExecutiveSummary(BaseModel):
    total_sources_consulted: Optional[int] = None
    deduplication_efficiency_rate: Optional[float] = None
    overall_quality_grade: Optional[str] = None
    best_performing_source: Optional[str] = None
    key_strengths: List[str]
    key_improvement_areas: List[str]

class ExpandDifferentialDiagnosisInput(BaseModel):
    presenting_complaint: Optional[str] = None
    location_if_pain: Optional[str] = None
    student_initial_ddx_list: List[str]

class ExpandedDdxOutput(BaseModel):
    applied_approach_description: Optional[str] = None
    suggested_additional_diagnoses_with_rationale: List[str]

class FacilitateDDxAnalysisOutputModel(BaseModel):
    response: Optional[str] = None

class FacilitateDDxAnalysisSNAPPSInputModel(BaseModel):
    case_summary: Optional[str] = None
    differential_diagnoses: List[str]
    student_analysis: Optional[str] = None
    case_context: Optional[str] = None

class FormulatedSearchStrategyOutput(BaseModel):
    refined_query_for_llm_synthesis: Optional[str] = None
    search_parameters_list: List["SearchParameters"]
    search_rationale: Optional[str] = None
    expected_evidence_types: List[str]

class HypothesisComparisonFeedback(BaseModel):
    hypothesis_name: Optional[str] = None
    feedback_on_supporting_findings: Optional[str] = None
    feedback_on_refuting_findings: Optional[str] = None
    feedback_on_discriminators: Optional[str] = None
    expert_comparison_points: Optional[List[str]] = None

class IllnessScriptInput(BaseModel):
    disease_name: Optional[str] = None

class IllnessScriptOutput(BaseModel):
    disease_name: Optional[str] = None
    predisposing_conditions: List[str]
    pathophysiology_summary: Optional[str] = None
    key_symptoms_and_signs: List[str]
    relevant_diagnostics: Optional[List[str]] = None

class LabAnalysisInput(BaseModel):
    lab_results: List["LabTestResult"]
    user_role: Optional[types.UserRole] = None
    patient_context: Optional[str] = None
    specific_user_query: Optional[str] = None

class LabInsightsOutput(BaseModel):
    patient_friendly_summary: Optional[str] = None
    potential_health_implications_patient: Optional[List[str]] = None
    lifestyle_tips_patient: Optional[List[str]] = None
    questions_to_ask_doctor_patient: Optional[List[str]] = None
    important_results_to_discuss_with_doctor: Optional[List[str]] = None
    professional_detailed_reasoning_cot: Optional[str] = None
    key_abnormalities_professional: Optional[List[str]] = None
    key_normal_results_with_context: Optional[List[str]] = None
    potential_patterns_and_correlations: Optional[List[str]] = None
    differential_considerations_professional: Optional[List[str]] = None
    suggested_next_steps_professional: Optional[List[str]] = None

class LabTestResult(BaseModel):
    test_name: Optional[str] = None
    value: Optional[str] = None
    unit: Optional[str] = None
    reference_range_low: Optional[str] = None
    reference_range_high: Optional[str] = None
    interpretation_flag: Optional[str] = None
    notes: Optional[str] = None

class PDFAnalysisInput(BaseModel):
    pdf_content: Optional[str] = None
    analysis_focus: Optional[str] = None
    clinical_question: Optional[str] = None

class PDFAnalysisOutput(BaseModel):
    document_type: Optional[str] = None
    key_findings: List[str]
    methodology_summary: Optional[str] = None
    clinical_relevance: Optional[str] = None
    evidence_quality: Optional[str] = None
    recommendations: List[str]
    limitations: List[str]
    structured_summary: Optional[str] = None

class PICOFormulationOutput(BaseModel):
    structured_pico_question: Optional["PICOQuestion"] = None
    explanation: Optional[str] = None
    pico_derivation_reasoning: Optional[str] = None
    search_terms_suggestions: List[str]
    boolean_search_strategies: List[str]
    alternative_pico_formulations: Optional[List[str]] = None
    recommended_study_types: List[str]

class PICOQuestion(BaseModel):
    patient_population: Optional[str] = None
    intervention: Optional[str] = None
    comparison: Optional[str] = None
    outcome: Optional[str] = None
    time_frame: Optional[str] = None
    study_type: Optional[str] = None

class PatientFollowUpChecklistOutput(BaseModel):
    checklist_items: List[str]
    when_to_contact_doctor_urgently: Optional[List[str]] = None
    general_advice: Optional[str] = None

class PatientFollowUpInput(BaseModel):
    consultation_summary_or_concept_explained: Optional[str] = None
    doctor_recommendations_summary: Optional[str] = None

class PlanEvaluationOutputModel(BaseModel):
    plan_strengths: List[str]
    plan_gaps: List[str]
    investigation_priorities: List[str]
    management_considerations: List[str]
    safety_concerns: List[str]
    cost_effectiveness_notes: List[str]
    guidelines_alignment: Optional[str] = None
    next_step_guidance: Optional[str] = None

class ProbeResponseOutputModel(BaseModel):
    answers_to_questions: List["AnsweredQuestion"]
    additional_considerations: List[str]
    counter_questions: List[str]
    knowledge_gaps_identified: List[str]
    learning_resources: List[str]

class ProblemRepresentationFeedbackOutputModel(BaseModel):
    feedback_strengths: List[str]
    feedback_improvements: List[str]
    missing_elements: List[str]
    overall_assessment: Optional[str] = None
    next_step_guidance: Optional[str] = None
    socratic_questions: List[str]

class ProcessingMetadata(BaseModel):
    total_processing_time_ms: Optional[float] = None
    sources_analyzed: Optional[int] = None
    timestamp: Optional[str] = None
    version: Optional[str] = None

class ProvideSessionSummarySNAPPSInputModel(BaseModel):
    session_history: List[str]
    case_context: Optional[str] = None
    student_selected_topic: Optional[str] = None

class QualityAssessment(BaseModel):
    overall_quality_grade: Optional[str] = None
    methodological_rigor_score: Optional[str] = None
    risk_of_bias_summary: Optional[str] = None
    applicability_concerns: List[str]
    reporting_quality: Optional[str] = None

class QualityScores(BaseModel):
    overall_score: Optional[float] = None
    coverage_score: Optional[float] = None
    diversity_score: Optional[float] = None
    recency_score: Optional[float] = None
    impact_score: Optional[float] = None
    source_balance_score: Optional[float] = None

class QuestionCategory(BaseModel):
    category_name: Optional[str] = None
    questions: List[str]
    category_rationale: Optional[str] = None

class RawSearchResultItem(BaseModel):
    source: Optional[types.ResearchSourceType] = None
    title: Optional[str] = None
    url: Optional[str] = None
    snippet_or_abstract: Optional[str] = None
    publication_date: Optional[str] = None
    authors: Optional[List[str]] = None
    journal: Optional[str] = None
    pmid: Optional[str] = None
    doi: Optional[str] = None
    study_type: Optional[str] = None
    citation_count: Optional[int] = None
    relevance_score: Optional[float] = None
    composite_impact_score: Optional[float] = None
    academic_source_name: Optional[str] = None

class ResearchMetrics(BaseModel):
    total_articles_analyzed: Optional[int] = None
    sources_consulted: List[str]
    search_duration_seconds: Optional[float] = None
    quality_filters_applied: List[str]
    date_range_searched: Optional[str] = None
    language_filters_applied: Optional[List[str]] = None
    search_strategy_summary: Optional[str] = None
    unique_journals_found: Optional[int] = None
    high_impact_studies_count: Optional[int] = None
    recent_studies_count: Optional[int] = None
    systematic_reviews_count: Optional[int] = None
    rct_count: Optional[int] = None
    cite_source_metrics: Optional["CiteSourceMetrics"] = None

class ResearchTaskInput(BaseModel):
    user_original_query: Optional[str] = None
    pico_question: Optional["PICOQuestion"] = None
    research_focus: Optional[str] = None
    target_audience: Optional[str] = None
    research_mode: Optional[str] = None

class SearchParameters(BaseModel):
    source: Optional[types.ResearchSourceType] = None
    query_string: Optional[str] = None
    max_results: Optional[int] = None
    study_type_filter: Optional[types.StudyTypeFilter] = None
    date_range_years: Optional[int] = None
    language_filter: Optional[str] = None
    rationale: Optional[str] = None

class SessionSummaryOutputModel(BaseModel):
    overall_performance: Optional[str] = None
    key_strengths: List[str]
    areas_for_development: List[str]
    learning_objectives_met: List[str]
    recommended_study_topics: List[str]
    metacognitive_insights: List[str]
    next_cases_suggestions: List[str]

class SimplifiedQueryOutput(BaseModel):
    simplified_query: Optional[str] = None

class SourceAnalysis(BaseModel):
    source_rankings: List["SourcePerformanceMetrics"]
    coverage_analysis: Optional[str] = None
    diversity_assessment: Optional[str] = None
    performance_insights: List[str]

class SourcePerformanceMetrics(BaseModel):
    source_name: Optional[str] = None
    total_results: Optional[int] = None
    unique_contributions: Optional[int] = None
    quality_score: Optional[float] = None
    response_time_ms: Optional[float] = None
    recent_publications_count: Optional[int] = None
    high_impact_count: Optional[int] = None

class StatisticalAssessment(BaseModel):
    sample_size_adequacy: Optional[str] = None
    statistical_methods_appropriateness: Optional[str] = None
    effect_size_interpretation: Optional[str] = None
    confidence_intervals_assessment: Optional[str] = None
    p_value_interpretation: Optional[str] = None
    multiple_comparisons_concern: Optional[str] = None

class StructuredSummaryOutput(BaseModel):
    one_sentence_summary: Optional[str] = None
    semantic_qualifiers_identified: List[str]
    key_patient_details_abstracted: List[str]
    suggested_areas_for_further_data_gathering: List[str]

class StudentHypothesisAnalysis(BaseModel):
    hypothesis_name: Optional[str] = None
    supporting_findings: List[str]
    refuting_findings: List[str]
    key_discriminators_against_others: List[str]

class SummaryFeedbackOutputModel(BaseModel):
    feedback_strengths: List[str]
    feedback_improvements: List[str]
    missing_elements: List[str]
    overall_assessment: Optional[str] = None
    next_step_guidance: Optional[str] = None
    socratic_questions: List[str]

class SynthesizedResearchOutput(BaseModel):
    original_query: Optional[str] = None
    executive_summary: Optional[str] = None
    professional_detailed_reasoning_cot: Optional[str] = None
    clinical_implications: List[str]
    key_findings_by_theme: List["EvidenceTheme"]
    research_gaps_identified: List[str]
    evidence_quality_assessment: Optional[str] = None
    relevant_references: List["RawSearchResultItem"]
    research_metrics: Optional["ResearchMetrics"] = None
    search_duration_seconds: Optional[float] = None

class TranslationOutput(BaseModel):
    translated_text: Optional[str] = None

class VisualDataSummary(BaseModel):
    chart_data_available: Optional[bool] = None
    supported_visualizations: List[str]
    data_summary: Optional[str] = None
