"""
This file contains a comprehensive dictionary of medical abbreviations in Portuguese.
It is designed to be used for quick lookups and to assist language models
in understanding and translating medical terminology present in clinical notes and other documents.

The dictionary maps abbreviations (as keys) to their full descriptions (as values).
All keys are standardized to uppercase for consistent and case-insensitive searching.
The list has been manually curated and cleaned from various sources to remove duplicates,
merge definitions, and standardize entries. For abbreviations with multiple meanings,
the different expansions are separated by ' OU '.
"""

PORTUGUESE_MEDICAL_ABBREVIATIONS = {
    'A/Ø': 'Amplitude/fluxo',
    'A+G': 'Água com glicose',
    'AA': 'Ar ambiente',
    'AAH': 'Abdome agudo hemorrágico',
    'AAI': 'Abdome agudo inflamatório',
    'AAO': 'Abdome agudo obstrutivo',
    'AAP': 'Abdome agudo perfurativo',
    'AAS': 'Ácido Acetilsalicílico (Aspirina)',
    'AAV': 'Abdome agudo vascular',
    'ABD': 'abdômen',
    'ABO': 'tipo sanguíneo ABO OU Sistema sanguíneo ABO',
    'ABVD': 'Doxorrubicina, bleomicina, vimblastina e dacarbazina',
    'AC': 'Doxorrubicina e Ciclofosfamida OU aparelho cardiovascular',
    'AC TH': 'Doxorrubicina, ciclofosfamida, paclitaxel e trastuzumabe',
    'AC-T': 'Doxorrubicina, Ciclofosfamida e taxano',
    'AC+': 'Ausculta Cervical Positiva',
    'AC-': 'Ausculta Cervical Negativa',
    'ACM': 'a critério médico OU arteria cerebral média',
    'ACTH': 'Hormônio Adrenocorticotrófico OU hormônio adrenocorticotrófico',
    'ACTP': 'Angioplastia Coronária Transluminal Percutânea',
    'AD': 'átrio direito',
    'ADH': 'Hormônio Antidiurético',
    'ADOC': 'Cisplatina, doxorrubicina, vincristina e ciclofosfamida',
    'ADP': 'Adenosina difosfato',
    'AE': 'átrio esquerdo',
    'AESP': 'atividade eletrica sem pulso OU Atividade elétrica sem pulso',
    'AIG': 'Adequado para Idade Gestacional',
    'AII': 'Angiotensina II',
    'AINE': 'Anti-Inflamatório Não-Esteroide',
    'AINH': 'Anti-Inflamatório Não-Hormonal',
    'AIDS/HIV': 'síndrome da imunodeficiência adquirida',
    'AIT': 'acidente isquêmico transitorio OU Ataque Isquêmico Transitório',
    'AK': 'aldrete Kroulik',
    'ALT': 'Altura',
    'AM': 'Aleitamento materno',
    'AMID': 'Artéria Mamária interna direita',
    'AMIE': 'Artéria Mamária interna esquerda',
    'AMP': 'ampola',
    'ANGIOCT': 'Angiotomografia computadorizada',
    'ANTI TPO': 'Antitireoperoxidase',
    'ANTIB': 'Antibiograma',
    'AO': 'Aorta',
    'AOE': 'abertura ocular espontânea',
    'AOP': 'avaliação dos pacientes',
    'AP': 'antecedentes pessoais OU Ausculta Pulmonar',
    'APA': 'Avaliação pré-anestésica',
    'APN': 'Asfixia perinatal',
    'AR': 'aparelho respiratório OU Ausculta respiratória',
    'ARA-C': 'Citarabina',
    'ARAC': 'Aracytin (ciratabina)',
    'ARV': 'Alteração da repolarização ventricular',
    'ASA': 'American Society of Anesthesiologists',
    'ASLO': 'Antiestreptolisina O',
    'ASP NT': 'Aspiração Nasotraqueal',
    'AT': 'Atresia Tricúspide',
    'AT3': 'Antitrombina III (atividade)',
    'ATB': 'Antimicrobiano',
    'ATC': 'angioplastia',
    'ATH TH': 'Doxorrubicina, paclitaxel, cicl fosfamida',
    'ATIC': 'Áudio Tonal Infantil Condicionada',
    'ATL': 'Audiometria Total Limiar',
    'ATM': 'Articulação temporo mandibular',
    'AU': 'Altura Uterina',
    'AV': 'Átrio Ventricular',
    'AVAS': 'Aspiração de Vias Aéreas Superiores',
    'AVC': 'acidente vascular cerebral (sinonimo de AVE)',
    'AVC / AVE': 'Acidente Vascular Cerebral/ Encefálico',
    'AVCH/ AVEH': 'Acidente Vascular Cerebral/ Encefálico Hemorrágico',
    'AVCI/AVEI': 'Acidente Vascular Cerebral/ Encefálico Isquêmico',
    'AVD': 'Atividade de vida diária',
    'AVDI': 'Atividade de vida diária instrumental',
    'AVE': 'acidente vascular encefálico',
    'AVEH': 'acidente vascular encefálico hemorrágico',
    'AVEI': 'acidente vascular encefálico isquêmico',
    'AVP': 'acesso venoso periférico',
    'AZT': 'Zidovudina',
    'BAV': 'bloqueio atrioventricular',
    'BAVT': 'bloqueio átrio ventricular total',
    'BCP': 'broncopneumonia',
    'BE': 'excesso de bases',
    'BEG': 'bom estado geral',
    'BGBL': 'Meio de cultura utilizado para leite humano',
    'BGN': 'Bacilo Gram Negativo',
    'BH': 'balanço hídrico',
    'BHCG': 'β Gonadotrofina Coriônica Humana',
    'BI': 'Bomba de infusão',
    'BIA': 'Balão Intra-aórtico',
    'BIC': 'bomba de infusão contínua',
    'BIP': 'Bomba Infusora Portátil',
    'BIPAP': 'Bi Level Positive Pressure Airway OU Positive Airway Pressure',
    'BIPCA': 'Bomba de Infusão para Analgesia Controlada',
    'BIS': 'Bispectral Index',
    'BK': 'Bacilo de Koch',
    'BLEO': 'Bleomicina',
    'BLH': 'Banco de leite humano',
    'BNF': 'bulhas normo fonéticas',
    'BNP': 'Peptídeo natriurético',
    'BP': 'Baixo peso',
    'BPM': 'batimento por minuto OU Batimentos Por Minuto',
    'BQL': 'Bronquiolite',
    'BR': 'Bolsa Rota',
    'BRA': 'Bloqueador do receptor de angiotensina',
    'BRD': 'bloqueio de ramo direito',
    'BRE': 'bloqueio de ramo esquerdo',
    'BRNF': 'Bulhas Rítmicas Normofonéticas',
    'BT': 'Bilirrubina Total',
    'BTF': 'Bilirrubina T + F',
    'BUMEL': 'Bussulfano e Melfalano',
    'BX': 'Biópsia',
    'C3': 'Complemento 3',
    'C4': 'Complemento 4',
    'CA': 'câncer',
    'CAE': 'Ciclofosfamida, doxorrubicina e etoposídeo',
    'CAF': 'Ciclofosfamida, doxorrubicina e fluoruracila',
    'CAI': 'Cálcio Iônico',
    'CAL': 'Calorias',
    'CALGB': 'Cisplatina, fluoruracila e 9781 radioterapia',
    'CAP': 'Ciclofosfamida, doxorrubicina e cisplatina',
    'CAPD': 'dialise peritoneal ambulatorial continua OU Diálise Peritoneal Ambulatorial Contínua',
    'CAPOX': 'Capecitabina e oxaliplatina',
    'CAPP': 'Ciclofosfamida, doxorrubicina, cisplatina e prednisona',
    'CARBO': 'Carboplatina',
    'CAT': 'cateterismo',
    'CATE': 'Cateterismo Cardíaco',
    'CATO2': 'Cateter de oxigênio',
    'CAU': 'Cateter arterial umbilical',
    'CAV': 'comunicação atrioventricular OU Ciclofosfamida, doxorrubicina e vincristina',
    'CB': 'Circunferência do braço',
    'CBC': 'Carcinoma basocelular',
    'CC': 'centro cirúrgico',
    'CCG': 'Cuidados e Controles Gerais',
    'CCIH': 'Comissão de Controle de Infecção Hospitalar',
    'CD': 'Coronária Direita OU conduta',
    'CDC': 'Center Disease Control',
    'CDDP': 'Cisplatina',
    'CEA': 'Concentração de antígeno carcinomaembrionário OU Antígeno carcinoembrionário',
    'CEC': 'Carcinoma espinocelular OU Circulação Extracorpórea',
    'CEST': 'complacência estática',
    'CFAR': 'Ciclofosfamida, fludarabina, alentuzumabe e rituximabe',
    'CH': 'concentrado de hemácias',
    'CHG': 'Gluconato de Clorexidina',
    'CHOEP': 'Ciclofosfamida, doxorrubicina, vincristina, etoposídeo, prednisona',
    'CHOP': 'Ciclofosfamida, doxorrubicina, vincristina e prednisona',
    'CIA': 'Comunicação Intra-Atrial',
    'CID': 'classificação internacional de doenças OU Código Internacional de Doenças',
    'CIPE': 'Cirurgia pediátrica',
    'CISCA': 'Ciclofosfamida, doxorrubicina e cisplatina',
    'CISFU-RT': 'Cisplatina, fluoruracila e adioterapia',
    'CIV': 'Comunicação Intraventricular OU comunicação interventricular',
    'CIVD': 'coagulação intravascular disseminada',
    'CK': 'Creatinoquinase',
    'CKM': 'Creatinofosfoquinase massa',
    'CKMB': 'fração da enzima CPK',
    'CL': 'Cloro',
    'CLAG-M': 'Cladribina, citarabina e mitoxantrona',
    'CM': 'centímetros OU Centímetro',
    'CMC': 'Clínica Médico-Cirúrgica',
    'CMED': 'Ciclofosfamida, metotrexato, etoposídeo, dexametasona',
    'CMF': 'Fluoruracila, metotrexate e ciclofosfamida',
    'CMFH': 'Fluoruracila, metotrexato e trastuzumabe',
    'CMV': 'Citomegalovírus OU Cisplatina, metotrexato, vimblastina',
    'CO2': 'Gás Carbônico',
    'CODOX': 'Ciclofosfamida, doxorrubicina, vincristina e metotrexato',
    'CODOX-M': 'Ciclofosfamida, doxorrubicina, vincristina, metotrexato e folinato de cálcio',
    'COMP': 'Comprimido',
    'CPAP': 'pressão positiva continua nas vias aéreas',
    'CPK': 'creatinina fosfoquinase',
    'CPM': 'Movimento Passivo Contínuo',
    'CPRE': 'Colangiopancreatografia retrógrada endoscópica',
    'CPT': 'capacidade pulmonar total',
    'CRF': 'capacidade residual funcional',
    'CT': 'tomografia computadorizada',
    'CV': 'capacidade vital',
    'CVC': 'cateter venoso central',
    'CVE': 'cardioversão elétrica',
    'CVF': 'Capacidade Vital Forçada',
    'CVP': 'Ciclofosfamida, vincristina e prednisona',
    'CVU': 'Cateter venoso umbilical',
    'CVVHDF': 'Hemodiafiltração',
    'CX': 'circunflexa',
    'DA': 'Descendente Anterior',
    'DAC': 'Doença Arterial Coronariana',
    'DAT': 'Dispositivo antitrombótico',
    'DBP': 'Displasia Broncopulmonar',
    'DBV': 'Dor em baixo ventre',
    'DC': 'débito cardíaco',
    'DCF': 'Docetaxel, cisplatina e fluoruracila',
    'DCT': 'Dobra cutânea triciptal',
    'DD': 'decúbito dorsal',
    'DDA': 'Doença Diarreica Aguda',
    'DDAVP': 'desmopressina OU Acetato de Desmopressina',
    'DDH': 'Decúbito Dorsal Horizontal',
    'DEA': 'Desfibrilador Elétrico Automático',
    'DEPO2': 'dependência de oxigênio',
    'DEX': 'Dexametosona',
    'DG': 'drágea OU diretoria geral',
    'DH': 'Doença hemolítica',
    'DH FEC': 'Docetaxel, trastuzumabe, fluoruracila, epirrubicina e ciclofosfamida',
    'DHAP': 'Dexametasona, cisplatina e citarabina',
    'DHEG': 'Doença Hipertensiva Espec fica da Gestação',
    'DHL': 'desidrogenase lática OU Desidrogenase Láctica',
    'DHRN': 'Doença hemorrágica do RN',
    'DI': 'diabetes insípidos',
    'DIH': 'dia de internação Hospitalar',
    'DIP': 'doença inflamatória pélvica OU Doença Inflamatória Pélvica',
    'DIU': 'Dispositivo Intrauterino',
    'DL': 'decilitro OU duplo lúmen',
    'DLD': 'decúbito lateral direito',
    'DLE': 'decúbito lateral esquerdo',
    'DLP': 'Dislipidemia',
    'DM': 'diabetes mellitus',
    'DMG': 'Diabetes mellitus gestacional',
    'DMID': 'diabetes mellitus insulinodependente',
    'DMNI': 'diabetes mellitus não insulinodependente',
    'DMO': 'Doença metabólica óssea',
    'DNA': 'Ácido Desoxirribonucleico',
    'DNPM': 'Desenvolvimento Neuropsicomotor',
    'DNV': 'Distúrbio Neurovegetativo',
    'DOCE': 'Docetaxel',
    'DOXO': 'Doxorrubicina',
    'DP': 'diálise peritoneal OU Derrame Pleural',
    'DPI': 'Diálise Peritoneal Intermitente',
    'DPMH': 'Doença Pulmonar da Membrana Hialina',
    'DPOC': 'doença pulmonar obstrutiva crônica',
    'DPP': 'Data Provável do Parto',
    'DPT': 'Difteria – Coqueluche – Tétano',
    'DR': 'Desconforto respiratório',
    'DRA': 'Desconforto respiratório adaptado',
    'DRC': 'doença renal crônica',
    'DRGE': 'doença do refluxo gastroesofágico',
    'DRRI': 'Desobstrução Rinofaríngea Retrógrada',
    'DSAV': 'Defeito de septo átrio ventricular',
    'DSLP': 'dislipidemia',
    'DST': 'Doença Sexualmente Transmissível',
    'DT': 'dreno de tórax',
    'DTA': 'diretoria técnica assistencial',
    'DTIC': 'Dacarbazina',
    'DU': 'Dinâmica Uterina',
    'DUM': 'Data da Última Menstruação',
    'DV': 'decúbito ventral',
    'DVA': 'Droga vasoativa',
    'DVE': 'derivação ventricular externa',
    'DVH': 'Decúbito ventral horizontal',
    'DVP': 'derivação ventricular peritoneal OU Derivação Ventrículo Peritoneal',
    'EAO': 'Estenose Aórtica',
    'EAP': 'Edema Agudo de Pulmão',
    'EBP': 'Extremo baixo peso',
    'EBV': 'Epstein-Baar Vírus',
    'EBV-G': 'Epstein-Baar IGG',
    'EBV-M': 'Epstein-Baar IGM',
    'EC': 'Estertores crepitantes',
    'ECA': 'Enzima conversora de angiotensina',
    'ECF': 'Epirrubicina, cisplatina e fluoruracila',
    'ECG': 'eletrocardiograma',
    'ECMO': 'Oxigenação Extracorpórea',
    'ECO': 'ecocardiograma OU Ecodopplercardiograma',
    'ECX': 'Epirrubicina, cisplatina e capecitabina',
    'EDA': 'Endoscopia Digestiva Alta',
    'EEG': 'eletroencefalograma',
    'EF': 'exame físico',
    'EGB': 'Estreptococos do grupo B',
    'ELA': 'Esclerose Lateral Amiotrófica',
    'EMLD': 'Episiotomia médio lateral direita',
    'EMTN': 'Equipe Multiprofissional de Terapia Nutricional',
    'EOA': 'Emissão Otoacústica',
    'EOAPD': 'Emissões OtoacústicasEvocadas por Produto de Distorção',
    'EOAT': 'Emissões Otoacústicas Transientes',
    'EOF': 'Epirrubicina, oxaliplatina e fluoruracila',
    'EOX': 'Epirrubicina, oxaliplatina e capecitabina',
    'EP': 'Etoposídeo e cisplatina',
    'EPAP': 'Pressão Positiva Expiratória',
    'EPOCH': 'Etoposídeo, doxorrubicina, vincristina, prednisona e cicl fosfamida',
    'ESBL': 'Bactérias Produtoras de Beta lactamase Extendida',
    'ESM': 'Estimulação sensório motora',
    'ETCO2': 'Fração expirada de CO2',
    'EV': 'endovenoso',
    'EVA': 'Escala visual analógica da dor',
    'EXP.': 'Expiração',
    'FA': 'fibrilação atrial',
    'FAB': 'Ferimento por Arma Branca',
    'FAC': 'Fluoruracila, doxorrubicina e ciclofosfamida',
    'FAF': 'Ferimento por Arma de Fogo',
    'FAL': 'Fosfatase alcalina',
    'FAN': 'Fator antinuclear',
    'FANT': 'Fontanela anterior normotensa',
    'FAV': 'fistula arteriovenosa',
    'FC': 'frequência cardíaca',
    'FCC': 'Ferimento Corto-Contuso',
    'FE': 'Fração de Ejeção',
    'FEES': 'Nasofibroscopia Funcional da Deglutição',
    'FEVE': 'Fração de ejeção do ventrículo esquerdo',
    'FID': 'Fossa Ilíaca Direita',
    'FIE': 'Fossa Ilíaca Esquerda',
    'FIO2': 'fração inspiratória de oxigênio',
    'FIV': 'Fertilização in vitro',
    'FLACC': 'Face leg activity crying consolability (Faces, Pernas, Braços, Choro e Consolabilidade)',
    'FO': 'Fundo de olho OU Ferida Operatória',
    'FR': 'frequência respiratória',
    'FSH': 'hormônio folículoestimulante OU Hormônio Folículo estimulante',
    'FV': 'fibrilação ventricular OU Fibrilação Ventricular',
    'FX': 'Fratura',
    'G+': 'gram positivo',
    'G-': 'gram negativo',
    'G6PD': 'Glicose-6-Fosfato Desidrogenase',
    'GECA': 'Gastroenterocolite aguda',
    'GGT': 'Gama GT',
    'GIG': 'Grande para Idade Gestacional',
    'GIST': 'Tumor Estromal Gastrointestinal',
    'GLG': 'Glicose',
    'GM-CSF': 'Fator de Crescimento de Colônias de Granulócitos e Monócitos',
    'GO': 'Ginecologia e Obstetrícia',
    'GPIIBIIIA': 'Glicoproteína IIb/IIIa',
    'GT(S)': 'Gota(s)',
    'GTT': 'Gastrostomia',
    'GV': 'Glóbulos vermelhos',
    'HAS': 'hipertensão arterial sistêmica',
    'HB': 'hemoglobina',
    'HBSAG': 'Antígeno de Superfície para Hepatite',
    'HBV': 'vírus da hepatite B',
    'HCD': 'Hemicorpo Direito',
    'HCE': 'Hemicorpo Esquerdo',
    'HCG': 'Gonadotrofina coriônica humana',
    'HCM': 'Hemoglobina Corpuscular Média',
    'HCV': 'virus da hepatite C OU Hepatite por Vírus C',
    'HD': 'hemodiálise OU Hipótese Diagnóstica',
    'HDA': 'história da doença atual OU hemorragia digestiva alta',
    'HDB': 'Hemorragia digestiva baixa',
    'HF': 'hemofiltração',
    'HIC': 'Hipertensão Intracraniana',
    'HIP': 'hematoma intraparenquimatoso',
    'HIPERCA': 'Hipercalcemia',
    'HIPERK': 'Hiperpotassemia',
    'HIPERMG': 'Hipermagnesemia',
    'HIPERNA': 'Hipernatremia',
    'HIV': 'Vírus da Imunodeficiência Humana',
    'HMC': 'Hemocultura',
    'HMD': 'Hemodiálise',
    'HMG': 'hemograma',
    'HP': 'hipertensão pulmonar',
    'HPMA': 'História Pregressa da Moléstia Atual',
    'HPV': 'Herpes Vírus Humano',
    'HSA': 'hemorragia subaracnóidea',
    'HT': 'Hematócrito',
    'HTA': 'histerectomia total abdominal',
    'HTC': 'hematócrito',
    'HTD': 'hemitórax direito',
    'HTE': 'hemitórax esquerdo',
    'HTV': 'histerectomia total via vaginal',
    'HVD': 'hipertrofia ventricular direita',
    'HVE': 'hipertrofia ventricular esquerda',
    'HYPER-CVAD': 'Rituximabe, ciclofosfamida, vincristina, doxorrubicina, dexametasona, metotrexato, folinato de cálcio, citarabina',
    'I AO': 'Insuficiência aórtica',
    'I MI': 'Insuficiência mitral',
    'I:E': 'Relação inspiratória:expiratória',
    'I.ABO': 'Incompatibilidade ABO',
    'I.RH': 'Incompatibilidade RH',
    'IAM': 'infarto agudo do miocárdio',
    'IAMCSST': 'infarto agudo do miocárdio com supradesnivelamento de ST',
    'IAMSSST': 'infarto agudo do miocárdio sem supradesnivelamento de ST',
    'IC': 'insuficiência cardíaca OU Índice Cardíaco',
    'ICC': 'insuficiência cardíaca congestiva',
    'ICFEP': 'insuficiência cardíaca com fração de ejeção preservada',
    'ICFER': 'insuficiência cardíaca com fração de ejeção reduzida',
    'ICO': 'Insuficiência Coronária Crônica',
    'ICS': 'Infecção de Corrente Sanguínea',
    'ID': 'intradérmica',
    'IECA': 'Inibidor Enzima Conversora de Angiotensina',
    'IFN': 'Alfainterferona',
    'IFO': 'Ifosfamida',
    'IG': 'Idade Gestacional',
    'IGA': 'Imunoblobulina A',
    'IGC': 'Idade Gestacional Corrigida',
    'IGE': 'Imunoblobulina E',
    'IGEV': 'Ifosfamida, gencitabina e vinorelbina',
    'IGG': 'Imunoblobulina G',
    'IGM': 'Imunoblobulina M',
    'IIC': 'Incompetência Istmo Cervical',
    'IL': 'Intralípide OU Interleucina',
    'ILA': 'Índice Líquido Amniótico',
    'IM': 'intramuscular',
    'IMC': 'Índice de Massa Corpórea',
    'INN': 'Icterícia Neonatal',
    'INSP.': 'Inspiração',
    'INT': 'Intubação nasotraqueal',
    'IOT': 'Intubação orotraqueal',
    'IPAP': 'Pressão Positiva Inspiratória',
    'IPM': 'Incursões por minuto',
    'IRA': 'insuficiência renal aguda',
    'IRC': 'insuficiência renal crônica',
    'IRPA': 'insuficiência respiratória aguda',
    'IRV': 'Irrigação Vesical (via de administração)',
    'IRVP': 'Índice de RVP',
    'IRVS': 'Índice de RVS',
    'IS': 'Índice Sistólico',
    'ISDA': 'Interrogatório sobre os diversos aparelhos',
    'ITU': 'Infecção do trato urinário',
    'IV': 'intravenoso',
    'IVAS': 'Infecção das Vias Aéreas Superiores',
    'K': 'potássio',
    'KCAL': 'Quilocaloria',
    'KCL': 'Cloreto de Potássio',
    'KG': 'quilograma(s)',
    'L-ASP': 'L-asparaginase',
    'LAM': 'Líquido amniótico meconial',
    'LBA': 'Lavado Broncoalveolar por Broncoscopia',
    'LCR': 'liquido cefalorraquidiano OU Líquido Céfalo - Raquidiano',
    'L.E.C.O': 'Litotripsia extracorpórea',
    'LER': 'Lesão por Esforços Repetitivos',
    'LES': 'lúpus eritematoso sistêmico',
    'LFD': 'Linfadenectomia',
    'LH': 'hormônio luteinizante OU Linfoma Hodking',
    'LHC': 'Leite humano cru',
    'LHF': 'Leite humano fortificado',
    'LHP': 'Leite humano pasteurizado',
    'LLA': 'Leucemia Linfoide Aguda',
    'LLC': 'Leucemia Linfoide Crônica',
    'LM': 'Leite materno',
    'LMA': 'Leucemia Mieloide Aguda',
    'LMC': 'Leucemia Mieloide Crônica',
    'LMP': 'Leite materno pasteurizado',
    'LMPV': 'Leucomalácea Periventricular',
    'LND': 'Linfadenectomia',
    'LNH': 'Linfoma Não-Hodking',
    'LNS': 'Linfonodo sentinela',
    'LP': 'Lesão por Pressão',
    'MBP': 'Muito Baixo Peso',
    'MCG': 'Micrograma(s)',
    'MCP': 'Marcapasso',
    'ME': 'Morte Encefálica',
    'MEFE': 'Medicina Fetal',
    'MEG': 'mal estado geral',
    'MF': 'Movimentação fetal',
    'MG': 'miligrama(s) OU magnésio OU Marginal',
    'MHB': 'Manobra de higiene brônquica',
    'MID': 'membro inferior direito',
    'MIE': 'membro inferior esquerdo',
    'MIELO': 'Mielograma',
    'MIN': 'minuto(s)',
    'MIPA': 'Moléstia inflamatória pélvica',
    'ML': 'mililitro',
    'MM': 'milímetro OU Mieloma Múltiplo',
    'MMHG': 'milímetros de mercúrio',
    'MMII': 'membros inferiores',
    'MMR': 'Vacina Combinada Contra Sarampo, Caxumba e Rubéola',
    'MMSS': 'membros superiores',
    'MOE': 'Motilidade Ocular Extrínseca',
    'MP': 'marcapasso',
    'MR': 'Multiresistente',
    'MRP': 'Manobra de reexpansão pulmonar',
    'MSD': 'membro superior direito',
    'MSE': 'membro superior esquerdo',
    'MTX': 'Metotrexato',
    'MULTI-R': 'Multirresistente',
    'MULTI-S': 'Multissensível',
    'MV': 'Murmúrio Vesicular',
    'MV+': 'murmúrio vesicular presente',
    'MV+ SEM': 'Murmúrio Vesicular presente sem',
    'NA': 'sódio OU Não se aplica',
    'NACL': 'Cloreto de Sódio',
    'NDN': 'Nada digno de nota',
    'NEC': 'Enterocolite necrosante',
    'NEM': 'Neoplasia Endócrina Múltipla',
    'NEO': 'Neoplasia',
    'NIPS': 'Neonatal Infant Pain Scale',
    'NORA': 'Noradrenalina',
    'NPH': 'Insulina Isofana - bovina, suína ou humana',
    'NPP': 'nutrição parenteral parcial OU Nutrição Parenteral',
    'NPT': 'nutrição parenteral total',
    'NTA': 'Necrose Tubular Aguda',
    'NVB': 'Vinorelbina',
    'O2': 'Oxigênio',
    'OA': 'Oligoâmnio',
    'OBS': 'Observação',
    'OD': 'olho direito',
    'OE': 'Olho Esquerdo',
    'OFIU': 'Óbito fetal intrauterino',
    'OMA': 'Otite Média Aguda',
    'OMS': 'Organização Mundial da Saúde',
    'ONCO': 'Oncologia ou oncológico',
    'OP': 'Osteopenia da prematuridade',
    'OT': 'Orotraqueal',
    'OVAS': 'Obstrução Vias Aéreas Superiores',
    'P. INSP.': 'Pressão inspiratória',
    'PA': 'pressão arterial',
    'PAAF': 'Punção aspirativa por agulha fina',
    'PAD': 'pressão arterial diastólica',
    'PAE': 'Pressão de Átrio Esquerdo',
    'PAI': 'Pressão arterial invasiva',
    'PAM': 'pressão arterial média',
    'PAI': 'Pressão Arterial Não Invasiva',
    'PAO2': 'pressão alveolar de oxigênio',
    'PAP': 'pressão da artéria pulmonar',
    'PAS': 'pressão arterial sistólica',
    'PAV': 'Pneumonia associada a ventilação mecânica',
    'PAVB': 'Proteína de alto valor biológico',
    'PC': 'Perímetro Cefálico',
    'PCA': 'Persistência do Canal Arterial',
    'PCO2': 'pressão parcial de gás carbônico',
    'PCP': 'Pressão Capilar Pulmonar',
    'PCR': 'parada cardiorrespiratória OU Proteína C Reativa',
    'PCTE': 'Paciente',
    'PCV': 'ventilação com pressão controlada OU Pressão controlada ventilatória',
    'PDAP': 'Pressão diastólica de artéria pulmonar',
    'PEATE': 'Potencial-evocado Auditivo de Tronco Encefálico',
    'PEEP': 'pressão positiva expiratória final',
    'PEFR': 'Pico da Frequência de Fluxo Expiratório',
    'PET': 'Tomografia com Emissão Pósitrons',
    'PF': 'Parto Fórceps',
    'PFC': 'Plasma Fresco Congelado',
    'PG': 'Prostraglandina',
    'PGF': 'Poligrafia',
    'PH': 'potencial de hidrogênio',
    'PIA': 'Pressão intra-abdominal',
    'PIC': 'pressão intracraniana',
    'PICC': 'Cateter Central de Inserção Periférica',
    'PIG': 'Pequeno para Idade Gestacional',
    'PINSP': 'Pressão Inspiratória',
    'PIP': 'pressão de pico inspiratório',
    'PIT': 'Pressão Intra Traqueal',
    'PL': 'punção lombar',
    'PLAQ': 'Plaquetas',
    'PMAP': 'Pressão média de artéria pulmonar',
    'PMP': 'Pressão média Pulmonar',
    'PN': 'Parto Normal',
    'PNM': 'pneumonia',
    'PO': 'Pós-Operatório',
    'PO2': 'Pressão de Oxigênio',
    'POAE': 'Posição Occipito Anterior Esquerda',
    'POI': 'pós-operatório imediato',
    'POT': 'pós-operatório tardio',
    'PPC': 'Pressão de Perfusão Cerebral',
    'PPF': 'Protoparasitológico de Fezes',
    'PQS': 'Pequena quantidade de secreção',
    'PRISM': 'Pediatric Risk of Mortality',
    'PS': 'pronto-socorro',
    'PSA': 'Antígeno Prostático Específico',
    'PSAL': 'antígeno prostático especifico livre',
    'PSAP': 'Pressão Sistólica na Artéria Pulmonar',
    'PSAT': 'antígeno prostático especifico total',
    'PSG': 'Polissonografia',
    'PSV': 'ventilação com pressão de suporte OU Pressão Suporte Ventilatória',
    'PT': 'Pré Termo',
    'PTF': 'Proteína Total e Frações',
    'PTH': 'Paratormônio',
    'PTI': 'Púrpura Trombocitopênica Idiopática',
    'PTN': 'Proteínas',
    'PTT': 'Púrpura Trombocitopênica Trombótica',
    'PTV': 'prostatectomia suprapúbica',
    'PVC': 'pressão venosa central',
    'QID': 'Quadrante Inferior Direito',
    'QIE': 'Quadrante Inferior Esquerdo',
    'QP': 'queixa principal',
    'QRS': 'complexo QRS do eletrocardiograma',
    'QSD': 'Quadrante Superior Direito',
    'QSE': 'Quadrante Superior Esquerdo',
    'QT': 'intervalo QT do eletrocardiograma OU Quimioterapia',
    'QTX': 'quimioterapia',
    'RA': 'ruídos adventícios',
    'RCE': 'retorno à circulação espontânea',
    'RCI': 'ritmo cardíaco irregular',
    'RCP': 'ressuscitação cardiopulmonar',
    'RCR': 'ritmo cardíaco regular',
    'REG': 'regular estado geral',
    'REOP': 'reoperação',
    'RHA': 'ruído hidroaéreo',
    'RJ': 'ritmo juncional',
    'RL': 'ringer lactato',
    'RNM': 'ressonância nuclear magnética',
    'RPA': 'recuperação pósanestésica',
    'RPM': 'respiração por minuto',
    'RS': 'ritmo sinusal',
    'RT': 'Radioterapia',
    'RTA': 'Reequilíbrio Tóraco Abdominal',
    'RTE': 'Radioterapia externa',
    'RTU': 'ressecção transuretal',
    'RTX': 'radioterapia',
    'RV': 'Reflexo vermelho',
    'RVP': 'Resistência Vascular Pulmonar',
    'RVS': 'Resistência Vascular Sistêmica',
    'RX': 'raios X',
    'S/N': 'se necessário',
    'SADT': 'Serviço Auxiliar de Diagnóstico e Terapia',
    'SAM': 'Síndrome de Aspiração Meconial',
    'SARA': 'síndrome da angústia respiratória aguda',
    'SAS': 'Escala de Agitação e Sedação',
    'SAT O2': 'Saturação de oxigênio',
    'SC': 'subcutâneo',
    'SCA': 'Síndrome Coronária Aguda',
    'SCD': 'Subclávia Direita',
    'SCE': 'Subclávia Esquerda',
    'SCIH': 'Serviço de Controle de Infecção Hospitalar',
    'SD': 'Síndrome',
    'SDR': 'Síndrome de Desconforto Respiratório',
    'SDRA': 'Síndrome do Desconforto Respiratório Agudo',
    'SEG': 'segundo',
    'SF': 'soro fisiológico OU Solução Fisiológica',
    'SG': 'soro glicosado OU Solução Glicosada',
    'SGF': 'Soro Glicofisiológico',
    'SHPPN': 'Síndrome da Hipertensão Pulmonar Persistente do RN',
    'SHU': 'Síndrome Hemolítica-Urêmica',
    'SIC': 'segundo informações colhidas OU Segundo Informações Coletadas',
    'SIDA': 'Síndrome da Imunodeficiência Adquirida Humana',
    'SIDS': 'Síndrome da Morte Súbita Infantil',
    'SIMV': 'ventilação mandatória intermitente sincronizada',
    'SIRS': 'Síndrome da Resposta Inflamatória',
    'SL': 'sublingual',
    'SM': 'Seio materno',
    'SMLD': 'Seio materno livre demanda',
    'SMNS': 'Síndrome da Morte Neonatal Súbita',
    'SN': 'Sucção nutritiva',
    'SNAPPE': 'Score for Neonatal Acute Phisology - Perinatal Extension',
    'SNC': 'sistema nervoso central',
    'SNE': 'sonda nasoenteral',
    'SNG': 'sonda nasogástrica',
    'SNN': 'Sucção não nutritiva',
    'SOB': 'Salpinooforectomia bilateral',
    'SOE': 'Sonda Oroenteral',
    'SOG': 'sonda orogástrica',
    'SOP': 'Síndrome do Ovário Policístico',
    'SPO2': 'saturação periférica de oxigênio',
    'SPU': 'Síndrome do Pulmão Úmido',
    'SSIADH': 'Síndrome Secreção Inapropriada do Hormônio Antidiurético',
    'SSVV': 'sinais vitais',
    'SVA': 'sondagem vesical de alivio OU Sonda Vesical de Alívio',
    'SVD': 'sondagem vesical de demora OU Sonda/Sondagem Vesical de Demora',
    'SVO2': 'Saturação venosa mista',
    'T.INSP.': 'Tempo Inspiratório',
    'T°': 'Temperatura',
    'T3': 'triiodotironina',
    'T4': 'tiroxina OU tetraiodotironina',
    'TALMO': 'Transplante Alogênico de Medula Óssea',
    'TAN': 'Triagem Auditiva Neonatal',
    'TAP': 'Tempo de atividade da protrombina',
    'TAUMO': 'Transplante Autólogo de Medula Óssea',
    'TAX': 'temperatura axilar',
    'TB': 'tuberculose OU Turbeculose',
    'TBI': 'Radioterapia Corporal Total',
    'TC': 'tomografia computadorizada OU tempo de coagulação',
    'TCE': 'traumatismo cranioencefalico',
    'TCM': 'Triglicerídeos de Cadeia Média',
    'TCTH': 'Transplante de Células Tronco Hematopoético',
    'TENS': 'Neuroestimulação elétrica transcutânea',
    'TEP': 'tromboembolismo pulmonar',
    'TEV': 'Tromboembolismo venoso',
    'TEXP': 'Tempo Expiratório',
    'TF': 'Tiragem de Fúrcula',
    'TG': 'Triglicerídeos',
    'TGA': 'Transposição de Grandes Artérias',
    'TGI': 'Trato Gastrointestinal',
    'TGO': 'transaminase glutamicooxalacetica',
    'TGP': 'transaminase glutamicopiruvica',
    'TGVB': 'Transposição dos Grandes Vasos da Base',
    'THAL': 'Talidomida',
    'TI': 'tempo inspiratório',
    'TINSP': 'Tempo Inspiratório',
    'TIPS': 'Shunt Portossistêmico Intra-hepático Transvenoso',
    'TM': 'Treino de Marcha',
    'TMO': 'Transplante de Medula Óssea',
    'TMX': 'Tamoxifeno',
    'TNF': 'Fator Necrose Tumoral',
    'TOC': 'Transtorno Obsessivo Compulsivo',
    'TOT': 'tubo oro traqueal',
    'TP': 'Trabalho de Parto OU Tempo de Protrombina',
    'TPM': 'Tensão Pré-Menstrual',
    'TPP': 'Trabalho de Parto Prematuro',
    'TPSV': 'Taquicardia paroxística supraventricular',
    'TQT': 'Traqueostomia',
    'TR': 'toque retal ou teste rápido',
    'TRH': 'Terapia de reposição hormonal',
    'TRM': 'Traumatismo Raquimedular',
    'TRN': 'Taquicardia por reentrada Nodal',
    'TRO': 'Terapia de Reidratação Oral',
    'TROP-I': 'Troponina I',
    'TRS': 'Transfusão Sanguínea',
    'TS': 'tempo de sangramento OU Tipagem sanguínea',
    'TSH': 'hormônio estimulante da tireóide OU Hormônio Tireoestimulante',
    'TSV': 'taquicardia supraventricular',
    'TT': 'Tempo de Trombina',
    'TTGO': 'Teste de Tolerância Oral à Glicose',
    'TTPA': 'tempo de tromboplastina parcial ativado OU Tempo de Tromboplastina Ativada',
    'TTRN': 'Taquipneia transitória do Recém-Nascido',
    'TU': 'tumor',
    'TV': 'taquicardia ventricular',
    'TVP': 'trombose venosa profunda',
    'TVSP': 'taquicardia ventricular sem pulso',
    'TX': 'transplante',
    'UCO': 'Unidade de Terapia Intensiva Coronariana',
    'UF': 'ultrafiltração',
    'UFC/ML': 'Unidade Formadora de Colônia',
    'UI': 'unidades internacionais',
    'UR': 'uréia',
    'URC': 'Urocultura',
    'US': 'ultra-sonografia',
    'USG': 'Ultrassonografia',
    'UTI': 'unidade de terapia intensiva',
    'UTI NEO': 'Unidade de Tratamento Intensivo Neonatal',
    'UTI-A': 'Unidade de Terapia Intensiva Adulto',
    'VAD': 'Via aérea difícil',
    'VAF': 'Ventilação de alta frequência',
    'VAS': 'vias aéreas superiores',
    'VC': 'volume corrente',
    'VCI': 'Veia cava inferior',
    'VCM': 'Volume Carpuscular Médio',
    'VCS': 'Veia cava superior',
    'VCV': 'ventilação controlada a volume',
    'VD': 'ventrículo direito',
    'VDG': 'Videodeglutograma',
    'VDRL': 'Venereal Disease Research Laboratory',
    'VDS': 'Volume diastólico final',
    'VE': 'ventrículo esquerdo',
    'VEF1': 'Volume Expiratório Forçado em 1 segundo',
    'VET': 'Valor energético total',
    'VFD': 'Veia Femural Direita',
    'VFE': 'Veia Femural Esquerda',
    'VHS': 'Velocidade de Sedimentação',
    'VIG': 'Velocidade Infusão Glicose',
    'VIT': 'Vitamina',
    'VJD': 'veia jugular direita',
    'VJE': 'veia jugular esquerda',
    'VLP': 'Videolaparoscopia',
    'VM': 'ventilação mecânica',
    'VMIN': 'volume minuto',
    'VNI': 'ventilação mecânica não invasiva',
    'VO': 'via oral',
    'VOL MIN': 'Volume minuto',
    'VPP': 'ventilação com pressão positiva',
    'VR': 'volume residual OU Via retal',
    'VRI': 'Volume reserva inspiratória',
    'VS': 'volume sistólico',
    'VSCD': 'veia subclávia direita',
    'VSCE': 'veia subclávia esquerda',
    'VT': 'Volume total',
    'VV': 'Via vaginal',
    'VVC': 'Ventilação por volume Controlado',
    'ZN': 'Zinco'  
}