name: Backend Tests (Python 3.11)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [ '3.11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: backend-api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run pytest
        working-directory: backend-api
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -q

