name: Sync Secrets from Infisical

on:
  workflow_dispatch:

jobs:
  vercel-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Infisical CLI
        run: npm i -g infisical
      - name: Export Infisical secrets (Production)
        env:
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
        run: |
          infisical export --env=Production --format=json > secrets.json
          jq '. | length' secrets.json
      - name: Push to Vercel Project Env (production)
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          for row in $(jq -r 'to_entries[] | @base64' secrets.json); do
            _jq() { echo ${row} | base64 -d | jq -r ${1}; }
            KEY=$(_jq '.key')
            VAL=$(_jq '.value')
            curl -sS -X POST "https://api.vercel.com/v10/projects/${VERCEL_PROJECT_ID}/env?upsert=1" \
              -H "Authorization: Bearer ${VERCEL_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"key\":\"${KEY}\",\"value\":\"${VAL}\",\"target\":[\"production\"],\"type\":\"plain\"}" > /dev/null
          done
          echo "Vercel sync complete"

